apiVersion: 1
datasources:
  - name: 'MySQL'
    type: 'mysql'
    access: 'proxy'
    url: 'mysql:3306'
    user: 'root'
    password: 'dibimbing'
    database: 'pet_adoption_db'
    jsonData:
      tlsSkipVerify: true
